
INSERT INTO UNIVERSITY (ID,NAME)
VALUES (1L,'NULP');

INSERT INTO DEPARTMENT (ID,NAME,UNIVERSITY_ID)
VALUES (1L, 'IKTA',1L);
INSERT INTO DEPARTMENT (ID,NAME,UNIVERSITY_ID)
VALUES (2L, 'IKNI',1L);
INSERT INTO DEPARTMENT (ID,NAME,UNIVERSITY_ID)
VALUES (3L, 'INPP',1L);


INSERT INTO LECTOR (ID,FIRST_NAME,LAST_NAME,SALARY,IS_HEAD,DEGREE,DEPARTMENT_ID)
VALUES (1L, 'Serhii', 'Venhrynovych',20000,true,'PROFESSOR',1)
;INSERT INTO LECTOR (ID,FIRST_NAME,LAST_NAME,SALARY,IS_HEAD,DEGREE,DEPARTMENT_ID)
VALUES (2L, 'John', 'Black',6000,false,'ASSISTANT',1);
INSERT INTO LECTOR (ID,FIRST_NAME,LAST_NAME,SALARY,IS_HEAD,DEGREE,DEPARTMENT_ID)
VALUES (3L, 'Ivan', 'Nord',7000,false,'ASSISTANT',2);
INSERT INTO LECTOR (ID,FIRST_NAME,LAST_NAME,SALARY,IS_HEAD,DEGREE,DEPARTMENT_ID)
VALUES (4L, 'Roman', 'Chorik',12000,false,'ASSOCIATE',3);
INSERT INTO LECTOR (ID,FIRST_NAME,LAST_NAME,SALARY,IS_HEAD,DEGREE,DEPARTMENT_ID)
VALUES (5L, 'Piter', 'Kumpel',9000,false,'ASSISTANT',3);