--University
CREATE TABLE UNIVERSITY (
  ID              BIGINT AUTO_INCREMENT,
  NAME            VARCHAR(500),
  PRIMARY KEY (ID)
  );

--Department
CREATE TABLE DEPARTMENT (
  ID              BIGINT AUTO_INCREMENT,
  NAME            VARCHAR(500),
  UNIVERSITY_ID   BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (UNIVERSITY_ID) REFERENCES UNIVERSITY(ID)
);

--Lector
CREATE TABLE LECTOR (
  ID              BIGINT AUTO_INCREMENT,
  FIRST_NAME      VARCHAR(100),
  LAST_NAME       VARCHAR(100),
  SALARY          DOUBLE,
  IS_HEAD         BOOLEAN,
  DEGREE          VARCHAR(100),
  DEPARTMENT_ID   BIGINT,
  PRIMARY KEY (ID),
  FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);